apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
replicas:
- count: 5
  name: vote
images:
- name: schoolofdevops/vote
  newTag: v4
namespace: instavote
commonAnnotations:
  supported-by: sre@team.com
configMapGenerator:
- envs:
  - options.env
  name: vote-options
labels:
- includeSelectors: true
  pairs:
    env: staging
    project: instavote
patches:
- path: deployment.yaml
- path: service.yaml
