apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
replicas:
- count: 1
  name: worker
images:
        - name: schoolofdevops/worker:latest
namespace: instavote
commonAnnotations:
  supported-by: sre@team.com
configMapGenerator:
labels:
- includeSelectors: true
  pairs:
    env: staging
    project: instavote
patches:
- path: deployment.yaml
